### ISSUE TITLE
August date display crashes

### ISSUE THREAD

**Issue by gcp** [RyanDam/Infocal#11]
If the date display includes the month name, it will crash in August. Observed myself and dozens of reports on the Connect IQ store.

**Comment by gcp** [comment]
I think this bug exists because the letter "G" does not have a kerningratio specified in this table: https://github.com/RyanDam/Infocal/blob/master/source/complication/ArcTextComplication.mc#L29

**Comment by RyanDam** [comment]
Thanks for figuring it out, I just notice many users report that they have a crash but I not manage to figurred why. Will fix it asap.
