### ISSUE TITLE
Add support for Forerunner 45?

### ISSUE THREAD

**Issue by saaadhu** [RyanDam/Infocal#4]
What would it take to add support for the Forerunner 45?

**Comment by RyanDam** [comment]
Currently I'm not have full tech specs of forerunner 45. This watchface will need at least 91KB of ram to be functional. Will have a check later.

**Comment by RyanDam** [comment]
Just did a check on forerunner 45. It only supports Connect IQ 1.0 (Infocal need at least 3.0), so  unless there is a software update, I can't support it for now.
