### ISSUE TITLE
Feature /help with setup

### ISSUE THREAD

**Issue by marcinbauer85** [RyanDam/Infocal#9]
Hi,
I'm a big fan of what you've done with this, really great work (also a paid supporter!). Ive been using this watchface since I bought my FR245 and haven't saw a watchface that came close to this :). This is a little random, but one feature would be useful for me. Is there a possibility to add a day/week counter since a particular day? So basically a reverse date countdown as you have now. This would help me (and may others I think) where people use the 'don't break the chain' method. Where you start to do something from a day, and count the days its passed since you started (and didn't break the chain).

If not, could you tell me if I can setup you project in VSCode to maybe try to program it myself? Im an UX/UI designer, and a semi front-end developer, but Garmin's IDE is a little over my head to setup, but I've read there is a possibility to compile Garmin apps on VSCode (https://github.com/ghisguth/vscode-monkey-c)

Thanks!

**Comment by RyanDam** [comment]
Hi, I'm not use countdown feature so frequently but I remember if you set the day in the past, countdown is still works with a minus sign, am I correct? If not, I will have a look and add a new complication.
